# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    - cron: "0 */12 * * *"
    
  # Permite executar manualmente a Action.
  workflow_dispatch:

# Regras
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Verifica o repositório
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Repositório que será utilizado para gerar os arquivos.
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: DanielEloy # Seu nome de usuário
          #gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Exibe o status do repositório
      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

      # Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
